src/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
import debug_toolbar
import grappelli
from index import IndexView
from core.views import UserLoginView, UserLogoutView, UserRegistrationView, send_email, ActivateUser, UserProfileView, \
    UpdateUserProfileView

if settings.DEBUG:
    import debug_toolbar  # NOQA: F811

handler404 = 'students.views.custom_404_view'

urlpatterns = [
    path("__debug__/", include(debug_toolbar.urls)),
    path('grappelli/', include('grappelli.urls')),
    path("admin/", admin.site.urls),
    path("", IndexView.as_view(), name="index"),
    path("students/", include('students.urls')),
    path("groups/", include('groups.urls')),
    path("teachers/", include('teachers.urls')),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("register/", UserRegistrationView.as_view(), name="register"),
    path("send_email/", send_email, name="send_email"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUser.as_view(), name="activate_user"),
    path("profile/<int:user_id>/", UserProfileView.as_view(), name="user_profile"),
    path("profileupdate/<int:user_id>/", UpdateUserProfileView.as_view(), name="update_user_profile"),
    path("oauth/", include("social_django.urls", namespace="social"))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/students/urls.py
from django.urls import path
from students.views import CreateStudent, UpdateStudent, DeleteStudent, GetStudents

app_name = "students"

urlpatterns = [
    path('', GetStudents.as_view(), name='get_students'),
    path('create/', CreateStudent.as_view(), name='create_student'),
    path('update/<uuid:uuid>/', UpdateStudent.as_view(), name='update_student'),
    path('delete/<uuid:uuid>/', DeleteStudent.as_view(), name='delete_student'),
]

src/students/models.py
from django.db import models
from faker import Faker
from core.models import Person
from uuid import uuid4
# Create your models here.


class Student(Person):
    uuid = models.UUIDField(default=uuid4, primary_key=True, unique=True, editable=False, db_index=True)
    enrollment = models.BooleanField(default=False)
    group = models.ForeignKey("groups.Group", on_delete=models.CASCADE, default=None, related_name="students")
    avatar = models.ImageField(upload_to="avatar/students/", default="avatar/default.jpg")
    resume = models.FileField(upload_to="resume/students/", blank=True, null=True)

    def __str__(self):
        return (f"{self.first_name} {self.last_name} {self.email} {self.date_of_birth} {self.phone_number}"
                f"{self.address} ({self.uuid})")

    @classmethod
    def generate_students(cls, count: int) -> None:
        faker = Faker()
        for i in range(count):
            student = Student(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                phone_number=faker.phone_number(),
                address=faker.address(),
                date_of_birth=faker.date_of_birth(minimum_age=16, maximum_age=60),
                enrollment=faker.random_element([True, False]),
            )
            student.save()

src/students/forms.py
from django.forms import ModelForm

from students.models import Student


class StudentForm(ModelForm):
    class Meta:
        model = Student
        fields = '__all__'

src/students/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.db.models import Q
from django.views.generic import CreateView, UpdateView, DeleteView, ListView

from students.forms import StudentForm
from students.models import Student


# Create your views here.

def custom_404_view(request, exception):
    return render(request, "errors/404.html", status=404)


class GetStudents(LoginRequiredMixin, ListView):
    template_name = "students/list.html"
    context_object_name = "students"
    queryset = Student.objects.all()

    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get('q')
        if search_query:
            or_filter = Q()
            search_field = [
                "first_name",
                "last_name",
                "email",
                "phone_number",
                "group__name",
                "date_of_birth",
            ]
            for field in search_field:
                or_filter |= Q(**{f"{field}__icontains": search_query})
            queryset = queryset.filter(or_filter)
        return queryset


class CreateStudent(LoginRequiredMixin, CreateView):
    template_name = "common/create.html"
    form_class = StudentForm
    success_url = reverse_lazy("students:get_students")


class UpdateStudent(LoginRequiredMixin, UpdateView):
    template_name = "common/update.html"
    form_class = StudentForm
    success_url = reverse_lazy("students:get_students")
    queryset = Student.objects.all()
    pk_url_kwarg = 'uuid'


class DeleteStudent(LoginRequiredMixin, DeleteView):
    template_name = 'common/delete.html'
    success_url = reverse_lazy("students:get_students")
    queryset = Student.objects.all()
    pk_url_kwarg = 'uuid'

src/templates/students/list.html
{% extends 'common/index.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row mb-3">
        <div class="col-auto">
            <form class="d-flex" method="GET" action="{% url 'students:get_students' %}" style="background-color: #f0f0f0; padding: 10px; border-radius: 5px;">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q" style="border: 1px solid #ccc; border-radius: 3px; padding: 5px;">
                <button class="btn btn-outline-primary" type="submit" style="background-color: #007bff; color: #fff; border: none; border-radius: 3px; padding: 5px 10px;">Search</button>
            </form>
        </div>
    </div>

    <table class="table table-hover table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">Avatar</th>
            <th scope="col">First name</th>
            <th scope="col">Last name</th>
            <th scope="col">Email</th>
            <th scope="col">Phone Number</th>
            <th scope="col">Birth Date</th>
            <th scope="col">Age</th>
            <th scope="col">Address</th>
            <th scope="col">Enrollment</th>
            <th scope="col">Group</th>
            <th scope="col">Resume</th>
            <th scope="col">Edit</th>
            <th scope="col">Delete</th>

        </tr>
        </thead>
        <tbody>
        {% for student in students %}
            <tr>
                <td><img src="{{ student.avatar.url }}" alt="Avatar" style="max-width: 50px;"></td>
                <td>{{ student.first_name }}</td>
                <td>{{ student.last_name }}</td>
                <td>{{ student.email }}</td>
                <td>{{ student.phone_number }}</td>
                {% if student.date_of_birth %}
                    <td>{{ student.date_of_birth }}</td>
                    <td>{{ student.age }}</td>
                {% else %}
                    <td>Unknown</td>
                    <td>Unknown</td>
                {% endif %}
                <td>{{ student.address }}</td>
                <td>{{ student.enrollment }}</td>
                <td>{{ student.group.name }}</td>
                <td>
                    {% if student.resume %}
                        <a href="{{ student.resume.url }}">{{ student.resume }}</a>
                    {% else %}
                        Empty
                    {% endif %}
                </td>
                <td>
                    <a type="button" class="btn btn-warning"
                       href={% url 'students:update_student' student.uuid %}>Edit
                    </a>
                </td>
                <td>
                    <a type="button" class="btn btn-danger"
                       href={% url 'students:delete_student' student.uuid %}>Delete
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}