src/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
import debug_toolbar
import grappelli
from index import IndexView
from core.views import UserLoginView, UserLogoutView, UserRegistrationView, send_email, ActivateUser, UserProfileView, \
    UpdateUserProfileView

if settings.DEBUG:
    import debug_toolbar  # NOQA: F811

handler404 = 'students.views.custom_404_view'

urlpatterns = [
    path("__debug__/", include(debug_toolbar.urls)),
    path('grappelli/', include('grappelli.urls')),
    path("admin/", admin.site.urls),
    path("", IndexView.as_view(), name="index"),
    path("students/", include('students.urls')),
    path("groups/", include('groups.urls')),
    path("teachers/", include('teachers.urls')),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("register/", UserRegistrationView.as_view(), name="register"),
    path("send_email/", send_email, name="send_email"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUser.as_view(), name="activate_user"),
    path("profile/<int:user_id>/", UserProfileView.as_view(), name="user_profile"),
    path("profileupdate/<int:user_id>/", UpdateUserProfileView.as_view(), name="update_user_profile"),
    path("oauth/", include("social_django.urls", namespace="social"))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/groups/urls.py
from django.urls import path
from groups.views import GetGroups, CreateGroup, UpdateGroup, DeleteGroup, GetInfoGroup

app_name = "groups"

urlpatterns = [
    path('', GetGroups.as_view(), name='get_groups'),
    path('create/', CreateGroup.as_view(), name='create_group'),
    path('update/<int:pk>/', UpdateGroup.as_view(), name='update_group'),
    path('delete/<int:pk>/', DeleteGroup.as_view(), name='delete_group'),
    path('info/<int:pk>/', GetInfoGroup.as_view(), name='group_info'),
]

src/teachers/urls.py
from django.urls import path
from teachers.views import GetTeachers, CreateTeacher, UpdateTeacher, DeleteTeacher

app_name = "teachers"

urlpatterns = [
    path('', GetTeachers.as_view(), name='get_teachers'),
    path('create/', CreateTeacher.as_view(), name='create_teacher'),
    path('update/<int:pk>/', UpdateTeacher.as_view(), name='update_teacher'),
    path('delete/<int:pk>/', DeleteTeacher.as_view(), name='delete_teacher'),
]

src/teachers/models.py
from django.db import models
from faker import Faker
from core.models import Person

# Create your models here.
groups = ["1A", "1B", "2A", "2B", "3A", "3B", "4A", "4B", None]
subjects = ["Math", "Law", "Astronomy", "History", "Chemistry", "Physics", "Sport"]


class Teacher(Person):
    subject = models.CharField(max_length=120)
    mentor_status = models.BooleanField(default=False)
    group = models.ManyToManyField('groups.Group', related_name='teachers')
    avatar = models.ImageField(upload_to="avatar/teachers/", default="avatar/default.jpg")

    def __str__(self):
        return (f"{self.first_name} {self.last_name} {self.email} {self.date_of_birth} {self.phone_number}"
                f"{self.address}")

    @classmethod
    def generate_teachers(cls, count: int) -> None:
        faker = Faker()
        for i in range(count):
            teacher = Teacher(
                first_name=faker.first_name(),
                last_name=faker.last_name(),
                email=faker.email(),
                phone_number=faker.phone_number(),
                address=faker.address(),
                date_of_birth=faker.date_of_birth(minimum_age=20, maximum_age=60),
                subject=faker.random_element(subjects),
                mentor_status=faker.random_element([True, False]),
                mentor_group=faker.random_element(groups),
            )
            teacher.save()

src/teachers/forms.py
from django.forms import ModelForm

from teachers.models import Teacher


class TeacherForm(ModelForm):
    class Meta:
        model = Teacher
        fields = '__all__'

src/teachers/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse_lazy

from django.db.models import Q
from django.views.generic import ListView, CreateView, UpdateView, DeleteView

from teachers.forms import TeacherForm
from teachers.models import Teacher


# Create your views here.


class GetTeachers(LoginRequiredMixin, ListView):
    template_name = "teachers/list.html"
    context_object_name = "teachers"
    queryset = Teacher.objects.all()

    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get('q')
        if search_query:
            or_filter = Q()
            search_fields = [
                "first_name",
                "last_name",
                "email",
                "phone_number",
                "date_of_birth",
                "subject",
                "group__name",
            ]
            for field in search_fields:
                or_filter |= Q(**{f"{field}__icontains": search_query})
            queryset = queryset.filter(or_filter)
        return queryset


class CreateTeacher(LoginRequiredMixin, CreateView):
    template_name = "common/create.html"
    form_class = TeacherForm
    success_url = reverse_lazy("teachers:get_teachers")


class UpdateTeacher(LoginRequiredMixin, UpdateView):
    template_name = "common/update.html"
    form_class = TeacherForm
    success_url = reverse_lazy("teachers:get_teachers")
    queryset = Teacher.objects.all()


class DeleteTeacher(LoginRequiredMixin, DeleteView):
    template_name = 'common/delete.html'
    success_url = reverse_lazy("teachers:get_teachers")
    queryset = Teacher.objects.all()

src/templates/teachers/list.html
{% extends 'common/index.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row mb-3">
        <div class="col-auto">
            <form class="d-flex" method="GET" action="{% url 'teachers:get_teachers' %}" style="background-color: #f0f0f0; padding: 10px; border-radius: 5px;">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q" style="border: 1px solid #ccc; border-radius: 3px; padding: 5px;">
                <button class="btn btn-outline-primary" type="submit" style="background-color: #007bff; color: #fff; border: none; border-radius: 3px; padding: 5px 10px;">Search</button>
            </form>
        </div>
    </div>

    <table class="table table-hover table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">Avatar</th>
            <th>First Name</th>
            <th>Last Name</th>
            <th>Email</th>
            <th>Phone Number</th>
            <th>Address</th>
            <th>Birth Date</th>
            <th>Age</th>
            <th>Mentor Status</th>
            <th>Mentor Group</th>

            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for teacher in teachers %}
            <tr>
                <td><img src="{{ teacher.avatar.url }}" alt="Avatar" style="max-width: 50px;"></td>
                <td>{{ teacher.first_name }}</td>
                <td>{{ teacher.last_name }}</td>
                <td>{{ teacher.email }}</td>
                <td>{{ teacher.phone_number }}</td>
                <td>{{ teacher.address }}</td>
                {% if teacher.date_of_birth %}
                    <td>{{ teacher.date_of_birth }}</td>
                    <td>{{ teacher.age }}</td>
                {% else %}
                    <td>Unknown</td>
                    <td>Unknown</td>
                {% endif %}
                <td>{{ teacher.mentor_status }}</td>
                <td>
                {% for group in teacher.group.all %}
                    <a href="{% url 'groups:group_info' group.pk %}" data-view-component="true" class="Link ml-2 text-bold">{{ group.name }}</a>
                    {% if not forloop.last %}, {% endif %}
                {% endfor %}
                </td>
                <td>
                    <a type="button" class="btn btn-warning"
                       href={% url 'teachers:update_teacher' teacher.pk %}>Edit
                    </a>
                </td>
                <td>
                    <a type="button" class="btn btn-danger"
                       href={% url 'teachers:delete_teacher' teacher.pk %}>Delete
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}