src/config/urls.py
from django.conf import settings
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
import debug_toolbar
import grappelli
from index import IndexView
from core.views import UserLoginView, UserLogoutView, UserRegistrationView, send_email, ActivateUser, UserProfileView, \
    UpdateUserProfileView

if settings.DEBUG:
    import debug_toolbar  # NOQA: F811

handler404 = 'students.views.custom_404_view'

urlpatterns = [
    path("__debug__/", include(debug_toolbar.urls)),
    path('grappelli/', include('grappelli.urls')),
    path("admin/", admin.site.urls),
    path("", IndexView.as_view(), name="index"),
    path("students/", include('students.urls')),
    path("groups/", include('groups.urls')),
    path("teachers/", include('teachers.urls')),
    path("login/", UserLoginView.as_view(), name="login"),
    path("logout/", UserLogoutView.as_view(), name="logout"),
    path("register/", UserRegistrationView.as_view(), name="register"),
    path("send_email/", send_email, name="send_email"),
    path("activate/<str:uuid64>/<str:token>/", ActivateUser.as_view(), name="activate_user"),
    path("profile/<int:user_id>/", UserProfileView.as_view(), name="user_profile"),
    path("profileupdate/<int:user_id>/", UpdateUserProfileView.as_view(), name="update_user_profile"),
    path("oauth/", include("social_django.urls", namespace="social"))
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

src/groups/urls.py
from django.urls import path
from groups.views import GetGroups, CreateGroup, UpdateGroup, DeleteGroup, GetInfoGroup

app_name = "groups"

urlpatterns = [
    path('', GetGroups.as_view(), name='get_groups'),
    path('create/', CreateGroup.as_view(), name='create_group'),
    path('update/<int:pk>/', UpdateGroup.as_view(), name='update_group'),
    path('delete/<int:pk>/', DeleteGroup.as_view(), name='delete_group'),
    path('info/<int:pk>/', GetInfoGroup.as_view(), name='group_info'),
]

src/groups/models.py
from django.db import models
from faker import Faker

# Create your models here.
groups = ["1A", "1B", "2A", "2B", "3A", "3B", "4A", "4B"]
subjects = ["Math", "Law", "Astronomy", "History", "Chemistry", "Physics", "Sport"]


class Group(models.Model):
    name = models.CharField(max_length=120)
    focus_on_subject = models.CharField(max_length=120)
    students_quantity = models.PositiveSmallIntegerField(default=0, blank=True, null=True)

    def __str__(self):
        return f"{self.name} {self.id}"

    @classmethod
    def generate_groups(cls, count: int) -> None:
        faker = Faker()
        for i in range(count):
            group = Group(
                name=faker.random_element(groups),
                focus_on_subject=faker.random_element(subjects),
                students_quantity=faker.random_int(min=1, max=30),
                mentor_first_name=faker.first_name(),
                mentor_last_name=faker.last_name(),
                mentor_email=faker.email(),
            )
            group.save()

src/groups/forms.py
from django.forms import ModelForm

from groups.models import Group


class GroupForm(ModelForm):
    class Meta:
        model = Group
        fields = '__all__'

src/groups/views.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.urls import reverse, reverse_lazy
from django.db.models import Q
from django.views.generic import ListView, CreateView, UpdateView, DeleteView, DetailView

from groups.forms import GroupForm
from groups.models import Group


# Create your views here.


class GetGroups(LoginRequiredMixin, ListView):
    template_name = "groups/list.html"
    context_object_name = "groups"
    queryset = Group.objects.all()

    def get_queryset(self):
        queryset = super().get_queryset()
        search_query = self.request.GET.get('q')
        if search_query:
            or_filter = Q()
            search_fields = [
                "name",
                "focus_on_subject",
                "students_quantity",
                "teachers__first_name",
                "teachers__last_name",
            ]
            for field in search_fields:
                or_filter |= Q(**{f"{field}__icontains": search_query})
            queryset = queryset.filter(or_filter)
        return queryset


class CreateGroup(LoginRequiredMixin, CreateView):
    template_name = "common/create.html"
    form_class = GroupForm
    success_url = reverse_lazy("groups:get_groups")


class UpdateGroup(LoginRequiredMixin, UpdateView):
    template_name = "common/update.html"
    form_class = GroupForm
    success_url = reverse_lazy("groups:get_groups")
    queryset = Group.objects.all()


class DeleteGroup(LoginRequiredMixin, DeleteView):
    template_name = 'common/delete.html'
    success_url = reverse_lazy("groups:get_groups")
    queryset = Group.objects.all()


class GetInfoGroup(LoginRequiredMixin, DetailView):
    template_name = "groups/group_info.html"
    context_object_name = "group"
    queryset = Group.objects.all()

src/templates/groups/group_info.html
{% extends 'common/index.html' %}
{% load crispy_forms_tags %}


{% block content %}
    <form method="get">
        <table class="table table-hover table-dark table-striped">
            <thead>
            <tr>
                <th>Group Name</th>
                <th>Focus on Subject</th>
                <th>Students Quantity</th>
                <th>Mentor</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <td>{{ group.name }}</td>
                <td>{{ group.focus_on_subject }}</td>
                <td>{{ group.students_quantity }}</td>
                <td>
                    {% for teacher in group.teachers.all %}
                            {{ teacher.first_name }}
                            {{ teacher.last_name }}
                            {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </td>
            </tr>
            </tbody>
        </table>
    </form>
{% endblock content %}

src/templates/groups/list.html
{% extends 'common/index.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <div class="row mb-3">
        <div class="col-auto">
            <form class="d-flex" method="GET" action="{% url 'groups:get_groups' %}" style="background-color: #f0f0f0; padding: 10px; border-radius: 5px;">
                <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search" name="q" style="border: 1px solid #ccc; border-radius: 3px; padding: 5px;">
                <button class="btn btn-outline-primary" type="submit" style="background-color: #007bff; color: #fff; border: none; border-radius: 3px; padding: 5px 10px;">Search</button>
            </form>
        </div>
    </div>

    <table class="table table-hover table-dark table-striped">
        <thead>
        <tr>
            <th scope="col">#</th>
            <th>Group Name</th>
            <th>Focus on Subject</th>
            <th>Students Quantity</th>
            <th>Mentor</th>
            <th>Edit</th>
            <th>Delete</th>
        </tr>
        </thead>
        <tbody>
        {% for group in groups %}
            <tr>
                <td>{{ group.pk }}</td>
                <td>{{ group.name }}</td>
                <td>{{ group.focus_on_subject }}</td>
                <td>{{ group.students_quantity }}</td>
                <td>
                    {% for teacher in group.teachers.all %}
                        {{ teacher.first_name }}
                        {{ teacher.last_name }}
                    {% endfor %}
                </td>
                <td>
                    <a type="button" class="btn btn-warning"
                       href={% url 'groups:update_group' group.pk %}>Edit
                    </a>
                </td>
                <td>
                    <a type="button" class="btn btn-danger"
                       href={% url 'groups:delete_group' group.pk %}>Delete
                    </a>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endblock content %}